export * from './show.object-type'
export * from './show.model'
export * from './shows.service'
export * from './dto/shows.args'
export * from './dto/show.args'
export * from './air-information/air-information.object-type'
export * from './show.schema'

export const SHOW_TYPE = 'show'
export const SHOWS_TYPE = 'shows'
